# Generated by Django 2.2.6 on 2019-11-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20191115_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodel',
            name='power_5',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
    ]
