# Generated by Django 2.2.6 on 2019-11-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_mainmodel_power_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodel',
            name='pH_value',
            field=models.DecimalField(decimal_places=2, default=7, max_digits=4),
        ),
    ]
