# Generated by Django 2.2.6 on 2019-11-25 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20191124_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodel',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
